apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: medpipeline
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: sc23fjrl/medpipeline:latest
          ports:
            - containerPort: 8080
