# service.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fastapi-app
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: sc23fjrl/fastapi-app:v1.1
          ports:
            - containerPort: 8080
