apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: fhirpipeline
spec:
  template:
    spec:
      containers:
        - image: sc23fjrl/fhirpipeline
          env:
            - name: OPENWEATHERMAP_API_KEY
              value: YOUR_API_KEY
